name: 1.1.3 Запуск прошивки

on:
  push:
    paths:
      - '112-blink/**'
      - '.github/workflows/check-1-1-3.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-1-1-3.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
